# Generated by Django 3.1 on 2022-12-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('fromUser', 'toUser')},
        ),
    ]
